# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\leichui\workspace\screenshot-master\ui\option.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Option(object):
    def setupUi(self, Dialog_Option):
        Dialog_Option.setObjectName("Dialog_Option")
        Dialog_Option.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_Option.resize(569, 230)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\leichui\\workspace\\screenshot-master\\ui\\../icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Option.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Option)
        self.buttonBox.setGeometry(QtCore.QRect(190, 170, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog_Option)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 541, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_api = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_api.setGeometry(QtCore.QRect(80, 20, 451, 21))
        self.lineEdit_api.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_api.setObjectName("lineEdit_api")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 55, 48, 16))
        self.label.setObjectName("label")
        self.requestURL = QtWidgets.QLabel(self.groupBox)
        self.requestURL.setGeometry(QtCore.QRect(20, 20, 54, 16))
        self.requestURL.setObjectName("requestURL")
        self.lineEdit_cookie = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cookie.setGeometry(QtCore.QRect(80, 55, 451, 21))
        self.lineEdit_cookie.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_cookie.setObjectName("lineEdit_cookie")

        self.retranslateUi(Dialog_Option)
        self.buttonBox.accepted.connect(Dialog_Option.accept)
        self.buttonBox.rejected.connect(Dialog_Option.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Option)

    def retranslateUi(self, Dialog_Option):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Option.setWindowTitle(_translate("Dialog_Option", "参数配置"))
        self.label.setText(_translate("Dialog_Option", "cookie"))
        self.requestURL.setText(_translate("Dialog_Option", "URL"))
